---
# Defaults tasks for role vdo-host

- name: Importing specific distro variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - vars

- name: Install the VDO packages
  ansible.builtin.dnf:
    name: "{{ vdo_pkgs_list }}"
    state: installed

- name: Create the volume group
  community.general.lvg:
    vg: "{{ vdo_vg_name }}"
    pvs: "{{ vdo_pv_disks }}"

- name: Setup VDO storage pool
  community.general.lvol:
    vg: "{{ vdo_vg_name }}"
    lv: "{{ vdo_lv_name }}"
    size: "{{ vdo_phys_size }}"
    opts: "--type vdo --vdosettings 'vdo_slab_size_mb={{ vdo_slab_size }}' --virtualsize {{ vdo_virt_size }}"
